secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
base_url="http://localhost"
notify_route="notify"
self_notify_channel="xxxx"
self_check_every_x_hours=24

[[clients]]
name="Nosee"
authorized_channels=["notifs","notifs-zautres"]
icon=":xxxx:"

[[clients]]
name="Eshop"
icon=":xxxx:"

[[slack_channels]]
name="notifs"
webhook_url="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[slack_channels]]
name="notifs-zautres"
webhook_url="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[slack_channels]]
name="francois"
webhook_url="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
