secret="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
baseurl="http://localhost"
notifyroute="notify"
selfnotifychannel="xxxx"
selfcheckeveryxhours=24

[[clients]]
name="Nosee"
authorizedChannels=["notifs","notifs-zautres"]

[[clients]]
name="Eshop"

[[slackChannels]]
name="notifs"
webhookUrl="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[slackChannels]]
name="notifs-zautres"
webhookUrl="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[slackChannels]]
name="francois"
webhookUrl="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
